version: "3.7"
networks:
  spendmanagement:
    external:
      name: spendmanagement-network

services:
  eventhandler:
    container_name: spendmanagement_eventhandler
    build:
      context: .
    image: spendmanagement_eventhandler:${APP_VERSION}
    environment:
      - APP_VERSION=${APP_VERSION}
    ports:
      - 8078:8080
    networks:
      - spendmanagement